title: <p align="center"> Sanjit</p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/sanjit-m-m-13b700184/">LinkedIn</a> |
  <a href="https://github.com/sanjitmm">GitHub</a>
  
  <br>   
  I'm working on Data Science, NLP, Python etc...
  <br>
  </p>



theme: jekyll-theme-minimal
